# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "account": "user1",
  "username" : "test1",
  "password" : "1234",
  "email" : "user1@dgsw.hs.kr",
  "address" : "aaaaaaa"
}

###

###

POST http://localhost:8080/user/login
Content-Type: application/json

{
  "account": "user1",
  "username" : "test10",
  "password" : "1234",
  "email" : "user10@dgsw.hs.kr"
}



###
###
POST http://localhost:8080/product/comment
Content-Type: application/json

{
  "title": "aaa",
  "productId" : "1",
  "userId" : "1",
  "email" : "user1@dgsw.hs.kr",
  "address" : "aaaaaaa"
}

###